version: '2.3'

services:

# redishoneypot service
  redishoneypot:
    # build: .
    container_name: redishoneypot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    network_mode: "host"
    image: "hary654321/redishoneypot"
    read_only: true
    volumes:
     - $PWD/data/redishoneypot/log:/var/log/redishoneypot
